---@meta
--==================================================================================================
--  $Id: common.ai,v 1.6 2005/04/25 16:57:46 jeffpang Exp $
--==================================================================================================
DebugS=nil               ---@type fun(str: string) (native)
DebugFI=nil              ---@type fun(str: string, val: integer) (native)
DebugUnitID=nil          ---@type fun(str: string, val: integer) (native)
DisplayText=nil          ---@type fun(p: integer, str: string) (native)
DisplayTextI=nil         ---@type fun(p: integer, str: string, val: integer) (native)
DisplayTextII=nil        ---@type fun(p: integer, str: string, v1: integer, v2: integer) (native)
DisplayTextIII=nil       ---@type fun(p: integer, str: string, v1: integer, v2: integer, v3: integer) (native)
DoAiScriptDebug=nil      ---@type fun(): boolean (native)

GetAiPlayer=nil          ---@type fun(): integer (native)
GetHeroId=nil            ---@type fun(): integer (native)
GetHeroLevelAI=nil       ---@type fun(): integer (native)

GetUnitCount=nil         ---@type fun(unitid: integer): integer (native)
GetPlayerUnitTypeCount=nil ---@type fun(p: player, unitid: integer): integer (native)
GetUnitCountDone=nil     ---@type fun(unitid: integer): integer (native)
GetTownUnitCount=nil     ---@type fun(id: integer, tn: integer, dn: boolean): integer (native)
GetUnitGoldCost=nil      ---@type fun(unitid: integer): integer (native)
GetUnitWoodCost=nil      ---@type fun(unitid: integer): integer (native)
GetUnitBuildTime=nil     ---@type fun(unitid: integer): integer (native)

GetMinesOwned=nil        ---@type fun(): integer (native)
GetGoldOwned=nil         ---@type fun(): integer (native)
TownWithMine=nil         ---@type fun(): integer (native)
TownHasMine=nil          ---@type fun(townid: integer): boolean (native)
TownHasHall=nil          ---@type fun(townid: integer): boolean (native)

GetUpgradeLevel=nil      ---@type fun(id: integer): integer (native)
GetUpgradeGoldCost=nil   ---@type fun(id: integer): integer (native)
GetUpgradeWoodCost=nil   ---@type fun(id: integer): integer (native)
GetNextExpansion=nil     ---@type fun(): integer (native)
GetMegaTarget=nil        ---@type fun(): unit (native)
GetBuilding=nil          ---@type fun(p: player): unit (native)
GetEnemyPower=nil        ---@type fun(): integer (native)
SetAllianceTarget=nil    ---@type fun(id: unit) (native)
GetAllianceTarget=nil    ---@type fun(): unit (native)

SetProduce=nil           ---@type fun(qty: integer, id: integer, town: integer): boolean (native)
Unsummon=nil             ---@type fun(unitid: unit) (native)
SetExpansion=nil         ---@type fun(peon: unit, id: integer): boolean (native)
SetUpgrade=nil           ---@type fun(id: integer): boolean (native)
SetHeroLevels=nil        ---@type fun(func: function) (native)
SetNewHeroes=nil         ---@type fun(state: boolean) (native)
PurchaseZeppelin=nil     ---@type fun() (native)

MergeUnits=nil           ---@type fun(qty: integer, a: integer, b: integer, make: integer): boolean (native)
ConvertUnits=nil         ---@type fun(qty: integer, id: integer): boolean (native)

SetCampaignAI=nil        ---@type fun() (native)
SetMeleeAI=nil           ---@type fun() (native)
SetTargetHeroes=nil      ---@type fun(state: boolean) (native)
SetPeonsRepair=nil       ---@type fun(state: boolean) (native)
SetRandomPaths=nil       ---@type fun(state: boolean) (native)
SetDefendPlayer=nil      ---@type fun(state: boolean) (native)
SetHeroesFlee=nil        ---@type fun(state: boolean) (native)
SetHeroesBuyItems=nil    ---@type fun(state: boolean) (native)
SetWatchMegaTargets=nil  ---@type fun(state: boolean) (native)
SetIgnoreInjured=nil     ---@type fun(state: boolean) (native)
SetHeroesTakeItems=nil   ---@type fun(state: boolean) (native)
SetUnitsFlee=nil         ---@type fun(state: boolean) (native)
SetGroupsFlee=nil        ---@type fun(state: boolean) (native)
SetSlowChopping=nil      ---@type fun(state: boolean) (native)
SetCaptainChanges=nil    ---@type fun(allow: boolean) (native)
SetSmartArtillery=nil    ---@type fun(state: boolean) (native)
SetReplacementCount=nil  ---@type fun(qty: integer) (native)
GroupTimedLife=nil       ---@type fun(allow: boolean) (native)
RemoveInjuries=nil       ---@type fun() (native)
RemoveSiege=nil          ---@type fun() (native)

InitAssault=nil          ---@type fun() (native)
AddAssault=nil           ---@type fun(qty: integer, id: integer): boolean (native)
AddDefenders=nil         ---@type fun(qty: integer, id: integer): boolean (native)

GetCreepCamp=nil         ---@type fun(min: integer, max: integer, flyers_ok: boolean): unit (native)

StartGetEnemyBase=nil    ---@type fun() (native)
WaitGetEnemyBase=nil     ---@type fun(): boolean (native)
GetEnemyBase=nil         ---@type fun(): unit (native)
GetExpansionFoe=nil      ---@type fun(): unit (native)
GetEnemyExpansion=nil    ---@type fun(): unit (native)
GetExpansionX=nil        ---@type fun(): integer (native)
GetExpansionY=nil        ---@type fun(): integer (native)
SetStagePoint=nil        ---@type fun(x: number, y: number) (native)
AttackMoveKill=nil       ---@type fun(target: unit) (native)
AttackMoveXY=nil         ---@type fun(x: integer, y: integer) (native)
LoadZepWave=nil          ---@type fun(x: integer, y: integer) (native)
SuicidePlayer=nil        ---@type fun(id: player, check_full: boolean): boolean (native)
SuicidePlayerUnits=nil   ---@type fun(id: player, check_full: boolean): boolean (native)
CaptainInCombat=nil      ---@type fun(attack_captain: boolean): boolean (native)
IsTowered=nil            ---@type fun(target: unit): boolean (native)

ClearHarvestAI=nil       ---@type fun() (native)
HarvestGold=nil          ---@type fun(town: integer, peons: integer) (native)
HarvestWood=nil          ---@type fun(town: integer, peons: integer) (native)
GetExpansionPeon=nil     ---@type fun(): unit (native)

StopGathering=nil        ---@type fun() (native)
AddGuardPost=nil         ---@type fun(id: integer, x: number, y: number) (native)
FillGuardPosts=nil       ---@type fun() (native)
ReturnGuardPosts=nil     ---@type fun() (native)
CreateCaptains=nil       ---@type fun() (native)
SetCaptainHome=nil       ---@type fun(which: integer, x: number, y: number) (native)
ResetCaptainLocs=nil     ---@type fun() (native)
ShiftTownSpot=nil        ---@type fun(x: number, y: number) (native)
TeleportCaptain=nil      ---@type fun(x: number, y: number) (native)
ClearCaptainTargets=nil  ---@type fun() (native)
CaptainAttack=nil        ---@type fun(x: number, y: number) (native)
CaptainVsUnits=nil       ---@type fun(id: player) (native)
CaptainVsPlayer=nil      ---@type fun(id: player) (native)
CaptainGoHome=nil        ---@type fun() (native)
CaptainIsHome=nil        ---@type fun(): boolean (native)
CaptainIsFull=nil        ---@type fun(): boolean (native)
CaptainIsEmpty=nil       ---@type fun(): boolean (native)
CaptainGroupSize=nil     ---@type fun(): integer (native)
CaptainReadiness=nil     ---@type fun(): integer (native)
CaptainRetreating=nil    ---@type fun(): boolean (native)
CaptainReadinessHP=nil   ---@type fun(): integer (native)
CaptainReadinessMa=nil   ---@type fun(): integer (native)
CaptainAtGoal=nil        ---@type fun(): boolean (native)
CreepsOnMap=nil          ---@type fun(): boolean (native)
SuicideUnit=nil          ---@type fun(count: integer, unitid: integer) (native)
SuicideUnitEx=nil        ---@type fun(ct: integer, uid: integer, pid: integer) (native)
StartThread=nil          ---@type fun(func: function) (native)
Sleep=nil                ---@type fun(seconds: number) (native)
UnitAlive=nil            ---@type fun(id: unit): boolean (native)
UnitInvis=nil            ---@type fun(id: unit): boolean (native)
IgnoredUnits=nil         ---@type fun(unitid: integer): integer (native)
TownThreatened=nil       ---@type fun(): boolean (native)
DisablePathing=nil       ---@type fun() (native)
SetAmphibious=nil        ---@type fun() (native)

CommandsWaiting=nil      ---@type fun(): integer (native)
GetLastCommand=nil       ---@type fun(): integer (native)
GetLastData=nil          ---@type fun(): integer (native)
PopLastCommand=nil       ---@type fun() (native)
MeleeDifficulty=nil      ---@type fun(): integer (native)